apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bpdmsfilestorage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmsfilestorage
    spec:
      containers:
        - name: bpdmsfilestorage
          image: cstarregistry.azurecr.io/bpdmsfilestorage
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
      hostAliases:
        - hostnames:
            - bpd-hub-dev.servicebus.windows.net
          ip: 10.70.5.9