apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bpdmsfilestorage 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmsfilestorage 
    spec:
      containers:
        - name: bpdmsfilestorage 
          image: cstarregistry.azurecr.io/bpdmsfilestorage
          ports:
          - containerPort: 8080